name: DeepMHCIIpro
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.9
  - scipy>=1.10.1
  - scikit-learn>=1.0.2
  - click>=8.0.4
  - ruamel.yaml>=0.16.12
  - tqdm>=4.62.3
  - logzero>=1.7.0
  - numpy>=1.22.4,<2.0
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - --find-links https://pytorch-geometric.com/whl/torch-1.13.1+cu116.html
    - torch==1.13.1+cu116
